$env:PYTHONPATH = "$PSScriptRoot/../src;$env:PYTHONPATH"
# python -m video_rpa.cli multi --folder "F:\Download\4.5-虧成首富,從不要錢開始" --desc "劇情" --tags "崩壞星穹鐵道,honkaistarrail,虧成首富從不要錢開始" --playlist "崩壞:星穹鐵道"
# python -m video_rpa.cli multi --folder "F:\Download\2026-09-14-虛構敘事-立界開篇" --desc "練度展示於結尾" --tags "崩壞星穹鐵道,honkaistarrail,立界開篇" --playlist "崩壞:星穹鐵道-高難"
# python -m video_rpa.cli multi --folder "F:\Download\2026-08-17-忘卻之庭-掃除風暴" --desc "練度展示於結尾" --tags "崩壞星穹鐵道,honkaistarrail,掃除風暴" --playlist "崩壞:星穹鐵道-高難"
python -m video_rpa.cli multi --folder "F:\Download\2026-09-28-異相仲裁-落葉歸根-絕境王棋" --desc "練度展示於結尾" --tags "崩壞星穹鐵道,honkaistarrail,落葉歸根" --playlist "崩壞:星穹鐵道-高難"
# python -m video_rpa.cli multi --folder "F:\Download\2026-09-30-末日幻影-仙客天狼" --desc "練度展示於結尾,還是太簡單了" --tags "崩壞星穹鐵道,honkaistarrail,仙客天狼" --playlist "崩壞:星穹鐵道-高難"
# python -m video_rpa.cli multi --folder "F:\Download\2026-08-30-末日幻影-仙客天狼" --desc "練度展示於結尾,還是太簡單了" --tags "崩壞星穹鐵道,honkaistarrail,仙客天狼" --playlist "崩壞:星穹鐵道-高難"